### ISSUE TITLE
run_demo.bash error

### ISSUE THREAD

**Issue by bianheshan** [osrf/car_demo#69]
hansen@hansen-Lenovo-Legion-Y7000-1060:~/Project/car_demo-master$ ./run_demo.bash 
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
Traceback (most recent call last):
  File "/home/hansen/.local/bin/rocker", line 7, in <module>
    from rocker.cli import main
  File "/home/hansen/.local/lib/python2.7/site-packages/rocker/cli.py", line 21, in <module>
    from .core import DockerImageGenerator
  File "/home/hansen/.local/lib/python2.7/site-packages/rocker/core.py", line 164
    **arguments,
               ^
SyntaxError: invalid syntax

hansen@hansen-Lenovo-Legion-Y7000-1060:~/Project/car_demo-master$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

**Comment by bianheshan** [comment]
i have resolved this issue, using python 3.5 veresion.
sudo apt-get install python3-pip
pip3 install rocker
